learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url('^admin/', admin.site.urls),
    url('^users/', include(('users.urls', 'users'), namespace='users')),
    url('', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
]

learning_logs/urls.py
'''
定义learning_logs的URL模式
'''
from django.conf.urls import url
from . import views

urlpatterns = [
    # 主页
    url(r'^$', views.index, name='index'),
    # 显示所有的主题
    url(r'^topics/$', views.topics, name='topics'),
    # 特定主题的详细页面
    url(r'^topic/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    # 用于添加新主题的网页
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    # 用于添加新条目的页面
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    # 用于编辑条目的页面
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

users/urls.py
'''
为应用程序users定义URL模式
'''
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from . import views

urlpatterns = [
    # 登录页面
    url(r'^login/$', LoginView.as_view(template_name='users/login.html'), name="login"),
    # 注销
    url(r'^logout/$', views.logout_view, name='logout'),
    # 注册
    url(r'^register/$', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    '''用户学习的主题'''
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        '''返回模型字符串'''
        return self.text
class Entry(models.Model):
    '''学到的有关某个主题的具体知识'''
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE)
    # topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    class Mete:
        varbose_name_plural = 'entries'
    def __str__(self):
        if len(self.text)>50:
            return self.text[:50] + "..."
        return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm) :
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
class EntryForm(forms.ModelForm) :
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .models import Topic, Entry
from .forms import TopicForm, EntryForm, Entry
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    '''
    学习笔记的主页
    '''
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    '''
    显示所有的主题
    '''
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    '''
    显示单个主题及其所在的条目
    '''
    topic = Topic.objects.get(id=topic_id)
    # 确认请求的主题是否属于当前用户
    if topic.owner != request.user:
        return Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, "entries":entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    '''
    添加新主题
    '''
    if request.method != 'POST':
        # 未提交数据:创建一个新表单
        form = TopicForm()
    else:
        # POST提交的数据, 对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry (request, topic_id) :
    '''
    未提交数据, 创建一个空表单
    '''
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        return Http404
    if request.method != 'POST':
        # 未提交数据, 创建一个空表单
        form = EntryForm()
    else:
        # POST提交的数据, 对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            # 重定向
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id) :
    '''
    编辑既有条目
    '''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        return Http404
    if request.method != 'POST' :
        # 初次请求, 使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        # POST提交的数据, 对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid() :
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse

# Create your views here.
def logout_view(request) :
    '''
    注销用户
    '''
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))
def register(request) :
    '''
    注册新用户
    '''
    if request.method != 'POST' :
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # 让用户自动登陆, 再重定向到主页
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form':form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatibla" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>
            学习笔记
        </title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                            学习笔记
                        </a>
                    </button>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="{% url 'learning_logs:topics' %}">
                                主题
                            </a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li>
                                <a>
                                    你好, {{ user.username }}
                                </a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{% url 'users:register' %}">
                                    注册
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'users:login' %}">
                                    登录
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
                <div class="page-hearder">
                    {% block header %}
                    {% endblock header %}
                </div>
                <div>
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </nav>
    </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% block content %}
<p>
    <a href="{% url 'learning_logs:topic' topic.id %}">
        {{ topic }}
    </a>
</p>
<p>
    编辑内容
</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">
        保存编辑
    </button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block header %}
    <div class="jumbotron">
        <h1>
            跟踪你的学习
        </h1>
    </div>
{% endblock header %}
{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">
            注册你的账户
        </a>
        你的学习笔记
    </h2>
    <h2>
        w y l s n a a t, m a e
        s w y l
    </h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% block content %}
<p>
    <a href="{% url 'learning_logs:topic' topic.id %}">
        {{ topic }}
    </a>
</p>
<p>
    添加新内容
</p>
<form>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">
        添加新内容
    </button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}
<p>
    添加新的主题
</p>
<form action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">
        添加主题
    </button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}
<p>
    主题: {{ topic }}
</p>
<p>
    内容:
</p>
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">
        添加新内容
    </a>
</p>
<ul>
    {% for entry in entries %}
    <li>
        <p>
            {{ entry.date_added|date:'M d, Y H:i' }}
        </p>
        <p>
            {{ entry.text|linebreaks }}
        </p>
        <p>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">
                编辑内容
            </a>
        </p>
    </li>
    {% empty %}
    <li>
        尚未添加任何主题。
    </li>
    {% endfor %}
</ul>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p>
    主题
</p>
<ul>
    {% for topic in topics %}
        <li>
            <a href="{% url 'learning_logs:topic' topic.id %}">
                {{ topic }}
            </a>
        </li>
    {% empty %}
        <li>
            尚未添加任何主题。
        </li>
    {% endfor %}
</ul>
<a href="{% url 'learning_logs:new_topic' %}">
    添加新主题
</a>
{% endblock content %}

users/templates/users/login.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}
{% block header %}
    <h2>
        登录你的账号
    </h2>
{% endblock header %}
{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn btn-primary">
            登录
        </button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends 'learning_logs/base.html' %}
{% block content %}
<form action="{% url 'users:register' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">
        注册
    </button>
    <input type="hidden", name="next", value="{% url 'learning_logs:index' %}">
</form>
{% endblock content %}